spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3307/putian?useUnicode=true&characterEncoding=UTF8
        username: usr_putian
        password: usr_putian
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    view:
        prefix: /WEB-INF/view/
        suffix: .jsp
mybatis:
      mapperLocations: classpath:com/jamie/mapper/*.xml
      typeAliasesPackage: com.jamie.model
      mapperScanner: com.jamie.dao